import type { Pattern } from './patterns'

export const DE_PATTERNS: Pattern[] = [
  {
    id: 'puffery-heutige-welt',
    name: 'Einstiegsfloskel "in der heutigen digitalen Welt"',
    category: 'phrase',
    regex: /\bin der heutigen(?: digitalen| schnelllebigen| modernen| vernetzten)? welt\b|\bim (?:heutigen )?digitalen zeitalter\b|\bim zeitalter der digitalisierung\b|\bin einer welt, in der\b|\bin der heutigen zeit\b/giu,
    why: 'A content-free scene-setting opener (boilerplate) that frames any topic against a vague backdrop of "today\'s world" before saying anything specific.',
    suggestion: 'Delete the sentence and start with the specific claim or fact.',
  },
  {
    id: 'puffery-rolle-spielen',
    name: 'Floskel "spielt eine entscheidende Rolle"',
    category: 'phrase',
    regex: /\bspiel(?:t|en)\b[^.!?\n]{0,30}?\b(?:eine|die) (?:entscheidende|wichtige|zentrale|bedeutende|wesentliche|maßgebliche|immer größere) rolle\b|\bnimmt eine schlüsselrolle ein\b/giu,
    why: 'Puffery: importance is asserted with an empty intensifier instead of demonstrated with a mechanism or outcome.',
    suggestion: 'Name what the thing actually does: "X entscheidet über Y", "X übernimmt Y".',
  },
  {
    id: 'puffery-von-bedeutung',
    name: 'Floskel "von großer Bedeutung"',
    category: 'phrase',
    regex: /\bvon (?:entscheidender|zentraler|großer|wesentlicher|maßgeblicher|enormer) bedeutung\b/giu,
    why: 'The same puffery mechanism as "spielt eine Rolle": a weight-claim substitutes for an actual argument.',
    suggestion: 'State why it matters in concrete, checkable terms, or delete the sentence.',
  },
  {
    id: 'de-wichtig-zu-beachten',
    name: 'Füllfloskel "es ist wichtig zu beachten"',
    category: 'tone',
    regex: /\bes ist (?:wichtig|erwähnenswert|bemerkenswert|entscheidend)[^.!?\n]{0,40}dass\b|\bes gilt zu beachten\b|\bes sei darauf hingewiesen\b/giu,
    why: 'A hedge (Absicherungsfloskel) that announces the importance of a claim instead of making it; it pads the sentence and delays the point.',
    suggestion: 'Delete the frame and state the claim directly: "X ist Y" statt "Es ist wichtig zu beachten, dass X Y ist".',
  },
  {
    id: 'hedge-safety-formula',
    name: 'Absicherungsfloskel "es lässt sich nicht leugnen"',
    category: 'tone',
    regex: /\bes (?:lässt sich nicht leugnen|versteht sich von selbst|muss bedacht werden)[^.!?\n]{0,15}dass\b|\bin anbetracht dessen\b|\bunter berücksichtigung von\b/giu,
    why: 'Impersonal safety formulas let the writer assert something while grammatically distancing themselves from committing to it.',
    suggestion: 'Commit to the claim directly, or attribute it to a named source.',
  },
  {
    id: 'modal-hedge-kann',
    name: 'Hedging-Modal "kann dazu beitragen"',
    category: 'tone',
    regex: /\bkann dazu beitragen\b|\bkann (?:außerdem |auch |zudem |zusätzlich )?helfen\b|\bkönnen dabei (?:unterstützen|helfen)\b|\bkann dabei helfen\b/giu,
    minCount: 2,
    why: 'The weak modal "kann" turns every statement into an unfalsifiable possibility; clustered use flattens the text into permanent hedged uncertainty.',
    suggestion: 'State whether it does help, backed by a reason or source, rather than that it merely "can".',
  },
  {
    id: 'transition-zudem',
    name: 'Floskelhafte Übergänge (zudem, darüber hinaus …)',
    category: 'structure',
    phrases: ['zudem', 'darüber hinaus', 'des weiteren', 'ferner', 'überdies', 'nicht zuletzt'],
    minCount: 2,
    minPer1000Words: 8,
    why: 'Empty additive connectives glue sentences together without naming a logical relation; their density, not their presence, is the tell.',
    suggestion: 'Delete the connective or name the real relation: "deshalb", "allerdings", "zum Beispiel".',
  },
  {
    id: 'conclusion-zusammenfassend',
    name: 'Fazit-Formel "zusammenfassend lässt sich sagen"',
    category: 'structure',
    regex: /\b(?:zusammenfassend|abschließend) (?:lässt sich (?:sagen|festhalten|feststellen)|kann (?:gesagt|festgehalten) werden)\b|\binsgesamt lässt sich sagen\b|\bim großen und ganzen\b|\balles in allem\b|\bunterm strich\b/giu,
    why: 'A templated conclusion marker that restates the topic instead of adding a final insight — the German "in conclusion".',
    suggestion: 'End with the one non-obvious takeaway instead of restating the thesis.',
  },
  {
    id: 'not-only-but-also',
    name: 'Parallelismus "nicht nur … sondern auch"',
    category: 'structure',
    regex: /\bnicht nur\b[^.!?\n]{2,100}?\bsondern (?:auch )?/giu,
    minCount: 2,
    why: 'A rhetorical antithesis template that manufactures the appearance of two-part insight; repeated use is a pattern, not a choice.',
    suggestion: 'Keep at most one; rewrite the others with a plain "und" or as direct statements.',
  },
  {
    id: 'nominalization-cluster',
    name: 'Nominalstil-Kette ("die Umsetzung der Digitalisierung")',
    category: 'structure',
    regex: /(?<![\p{L}\p{N}])(?:die|der|des|zur|zum) \p{Lu}\p{L}*(?:ung|ierung|heit|keit|tion) (?:der|des) (?:\p{Ll}\p{L}* )?\p{Lu}\p{L}+/gu,
    minCount: 3,
    why: 'Chained nominalizations (Nominalstil) hide who does what to whom; generated formal German leans heavily on this bureaucratic register.',
    suggestion: 'Unpack the nouns into verbs with subjects: "wir digitalisieren die Verwaltung, damit …".',
  },
  {
    id: 'generic-challenge-closing',
    name: 'Herausforderungs-Coda "trotz ihrer Erfolge …"',
    category: 'structure',
    regex: /\btrotz (?:seiner|ihrer|dieser) erfolge\b[^.!?\n]{0,60}\bvor (?:mehreren|zahlreichen|einigen|großen) herausforderungen\b/giu,
    why: 'A content-free balance move: unspecified successes meet unspecified challenges, and nothing checkable is said.',
    suggestion: 'Name the actual obstacles ("Fachkräftemangel", "veraltete IT") instead of "Herausforderungen".',
  },
  {
    id: 'rhetorical-hook-opening',
    name: 'Rhetorischer Aufhänger "immer mehr Menschen fragen sich"',
    category: 'structure',
    regex: /\bimmer mehr menschen fragen sich\b/giu,
    why: 'An unsourced claim about growing collective sentiment used purely as a hook — nobody is cited, no number given.',
    suggestion: 'Replace with an actual statistic or a direct statement of the topic.',
  },
  {
    id: 'imperative-cta-closing',
    name: 'Call-to-Action-Schluss "Denken Sie daran …!"',
    category: 'tone',
    regex: /\bdenken sie daran\b[^.!?\n]{0,60}!|\bfangen sie noch heute an\b|\bworauf warten sie noch\b/giu,
    why: 'A motivational-coach imperative bolted onto an informational text — a genre mismatch borrowed from marketing copy.',
    suggestion: 'Delete the exhortation; end on the last substantive point.',
  },
  {
    id: 'weasel-vague-attribution',
    name: 'Vage Autoritätsberufung "viele Experten sind sich einig"',
    category: 'phrase',
    regex: /\b(?:viele|zahlreiche) experten sind sich einig\b|\bstudien zeigen,? dass\b|\bforscher haben herausgefunden\b|\bexperten zufolge\b/giu,
    why: 'Weasel wording: authority is borrowed from unnamed experts or studies, so the claim cannot be checked.',
    suggestion: 'Name the study or expert with year and source, or delete the claim.',
  },
  {
    id: 'marketing-eintauchen',
    name: 'Marketing-Imperativ "Tauchen Sie ein"',
    category: 'tone',
    regex: /\btauchen (?:wir|sie) (?:tiefer )?ein\b|\beintauchen in\b|\blassen sie uns eintauchen\b|\bentdecken sie die welt\b/giu,
    why: 'A calque of the English marketing verb "dive in" that clashes with the sober register of most German prose.',
    suggestion: 'Use a plain verb fitting the register: "betrachten wir", "im Folgenden geht es um …".',
  },
  {
    id: 'marketing-entfesseln',
    name: 'Marketing-Verb "entfesseln" / "aufs nächste Level"',
    category: 'tone',
    regex: /\bentfessel\p{L}*\b|\bpotenzial (?:freisetzen|ausschöpfen|entfalten)\b|\bauf(?:s| das) nächste level\b/giu,
    why: 'Quasi-heroic marketing verbs ("unleash", "next level") translated near-literally from English advertising copy.',
    suggestion: 'Name the concrete improvement: what gets better, by how much, for whom.',
  },
  {
    id: 'buzzword-adjective-stack',
    name: 'Buzzword-Adjektive (ganzheitlich, nahtlos, maßgeschneidert …)',
    category: 'word-choice',
    regex: /(?<![\p{L}\p{N}])(?:ganzheitlich|maßgeschneidert|nahtlos|facettenreich|vielschichtig|essenziell|vielfältig|nachhaltig)(?:e[nmrs]?)?(?![\p{L}\p{N}])/giu,
    minCount: 3,
    why: 'A rotation of safe, sophisticated-sounding filler adjectives; each has legitimate uses, but their clustering is the signal.',
    suggestion: 'Keep the single most precise adjective and replace the rest with checkable properties.',
  },
  {
    id: 'vielzahl-vague',
    name: 'Vage Mengenangabe "eine Vielzahl von"',
    category: 'word-choice',
    phrases: ['eine vielzahl von', 'eine vielzahl an', 'ein breites spektrum an', 'eine breite palette an', 'eine fülle von', 'eine fülle an'],
    minCount: 2,
    why: 'Vague quantity phrases avoid naming anything specific — safe filler that generated text overuses.',
    suggestion: 'Name two or three concrete examples, or give the actual number.',
  },
  {
    id: 'vorteile-bieten',
    name: 'Floskel "bietet zahlreiche Vorteile"',
    category: 'phrase',
    phrases: ['bietet zahlreiche vorteile', 'bietet viele vorteile', 'bietet eine vielzahl von vorteilen', 'ermöglicht es ihnen'],
    why: 'A benefits-claim template that promises value without naming a single concrete benefit.',
    suggestion: 'List the two or three actual advantages with specifics.',
  },
  {
    id: 'anglicism-calque',
    name: 'Lehnübersetzungen ("am Ende des Tages", "das macht Sinn")',
    category: 'word-choice',
    phrases: ['am ende des tages', 'das macht sinn', 'macht das sinn'],
    minCount: 2,
    why: 'Word-for-word calques of English idioms instead of the idiomatic German equivalent — a footprint of English-first generation (though increasingly common in spoken German).',
    suggestion: 'Use the native idiom: "letztlich"/"im Endeffekt"; "das ergibt Sinn"/"das leuchtet ein".',
  },
  {
    id: 'forced-metaphor',
    name: 'Aufgesetzte Stock-Metapher ("wie ein Fundament, auf dem …")',
    category: 'word-choice',
    regex: /\bwie ein leuchtturm\b|\bein fundament, auf dem\b/giu,
    why: 'Interchangeable stock metaphors that could be swapped into any topic — chosen for genre-typicality, not fit.',
    suggestion: 'Delete the metaphor or replace it with an image specific to the subject.',
  },
  {
    id: 'dash-overuse',
    name: 'Gedankenstrich-Häufung',
    category: 'punctuation',
    regex: /—|(?<=\s)–(?=\s)|(?<=\s)--(?=\s)/gu,
    minCount: 3,
    minPer1000Words: 12,
    why: 'Generated German uses the dash as an all-purpose parenthetical connector far above the human baseline; a single dash is normal punctuation, the density is the tell.',
    suggestion: 'Replace most dashes with commas, colons, or separate sentences; keep one deliberate break.',
  },
  {
    id: 'chatbot-collab-artifact',
    name: 'Chat-Reste ("Ich hoffe, das hilft", "Lassen Sie mich wissen")',
    category: 'chatbot-artifact',
    regex: /\bich hoffe, d(?:as|ies) hilft\b|\blassen sie mich wissen\b|\blass mich wissen\b|(?:^|[.!?]\s+|\n)(?:natürlich|sicherlich|gerne)!/giu,
    minCount: 2,
    why: 'Second-person conversational turn-markers addressed to a chat user; a single "lassen Sie mich wissen" is normal in an email, but the opener-plus-closer combination is the fingerprint of an unedited chatbot reply.',
    suggestion: 'Delete the sentence; it never belonged in the document\'s register.',
  },
  {
    id: 'chatbot-knowledge-cutoff',
    name: 'Wissens-Cutoff-Disclaimer',
    category: 'chatbot-artifact',
    regex: /\bbis zu meinem letzten (?:wissensstand|update|trainingsstand)\b|\bbasierend auf verfügbaren informationen bis\b|\bnach meinem letzten update\b|\bals ki-(?:modell|sprachmodell)\b/giu,
    why: 'A first-person disclaimer only a language model produces, referencing its own training cutoff.',
    suggestion: 'Delete it; add a real as-of date sourced independently if needed.',
  },
  {
    id: 'chatbot-letter-artifact',
    name: 'Brief-Artefakt ("Betreff:", "ich hoffe, diese Nachricht erreicht Sie")',
    category: 'chatbot-artifact',
    regex: /(?:^|\n)[ \t]*betreff[ \t]*:|\bich hoffe, diese nachricht erreicht sie\b|\bich schreibe, um\b|\bliebe leserinnen und leser\b/giu,
    why: 'The model defaulted to its most common training genre (email/letter) although the requested output was an article or report.',
    suggestion: 'Remove salutation and subject-line framing; start with the content.',
  },
  {
    id: 'placeholder-artifact',
    name: 'Unaufgelöste Platzhalter ("[Quelle einfügen]")',
    category: 'chatbot-artifact',
    regex: /\[(?:quelle|link|zitat|bild)(?: einfügen)?\]|\bgehe zu suche (?:nr\.?|nummer) ?\d+\b/giu,
    why: 'Bracketed placeholders or tool-call remnants are internal scaffolding that leaked into the final text — unambiguous evidence of unedited generation.',
    suggestion: 'Fill in the actual source or delete the sentence if none exists.',
  },
]
