import type { Pattern } from './patterns'

export const EN_PATTERNS: Pattern[] = [
  {
    id: 'delve',
    name: 'LLM-favorite verb "delve"',
    category: 'word-choice',
    phrases: ['delve into', 'delves into', 'delving into', 'delved into', 'delve deeper'],
    why: 'Corpus studies of LLM output found "delve" massively overrepresented in AI-generated text compared to human writing; it became the canonical AI tell.',
    suggestion: 'Use a plainer verb: "look at", "examine", or name the concrete action.',
  },
  {
    id: 'fast-paced-opener',
    name: 'Stock opener "in today\'s fast-paced world"',
    category: 'phrase',
    regex: /\bin (?:today['’]s|the current|this|an?) (?:fast-paced|ever-evolving|rapidly[- ]evolving|digital|modern)(?:,? (?:fast-paced|ever-evolving|rapidly[- ]evolving|digital|interconnected))? (?:world|landscape|age|era|environment)\b/giu,
    why: 'A content-free scene-setting hook (boilerplate) that fits any topic — generated text defaults to it when no specific opening fact is available.',
    suggestion: 'Open with a specific, concrete fact or claim instead of a generic scene-setter.',
  },
  {
    id: 'collaborative-address',
    name: 'Collaborative address "let\'s dive into"',
    category: 'tone',
    regex: /\b(?:let['’]s|we will|we['’]ll) (?:explore|dive into|delve into|examine|take a (?:closer )?look at|break down|navigate|unpack)\b/giu,
    why: 'First-person-plural guidance ("let\'s explore") is the assistant\'s conversational register leaking into prose that is not a dialogue.',
    suggestion: 'Start with the content itself instead of announcing that you will present it.',
  },
  {
    id: 'hedging-important-to-note',
    name: 'Hedging filler "it is important to note"',
    category: 'tone',
    regex: /\bit(?:['’]s| is) (?:important|worth|crucial|essential) (?:to note|noting|to mention|mentioning|to remember|to highlight)\b/giu,
    why: 'A hedge that announces importance instead of demonstrating it; it delays the point and pads the sentence (filler).',
    suggestion: 'Delete the phrase and keep the sentence that follows it.',
  },
  {
    id: 'puffery-testament',
    name: '"Stands as a testament" puffery',
    category: 'phrase',
    regex: /\b(?:stands? as|serves? as|is|was|remains?) a testament to\b|\bstands? as a reminder\b/giu,
    why: 'Puffery (peacock language): it asserts significance without saying who judged it significant or why.',
    suggestion: 'State the concrete fact and let it imply significance: "built in 100 CE, it still carries traffic today".',
  },
  {
    id: 'puffery-pivotal-role',
    name: 'Cliché "plays a pivotal role"',
    category: 'phrase',
    regex: /\bplay(?:s|ed|ing)? an? (?:pivotal|crucial|vital|significant|key|important) role\b/giu,
    why: 'A vague importance claim (undue emphasis): it asserts weight rhetorically instead of demonstrating it with a mechanism or outcome.',
    suggestion: 'Say what the thing actually does: "X handles Y", "X raised $2M".',
  },
  {
    id: 'puffery-rich-tapestry',
    name: 'Puffery metaphor "tapestry"',
    category: 'word-choice',
    regex: /\b(?:rich|vibrant|colorful|cultural) tapestry\b|\btapestry of\b/giu,
    why: 'An ornamental metaphor (borrowed grandeur) that decorates without adding information — a signature of generated filler prose.',
    suggestion: 'Name the actual elements instead: "Vietnamese, Hmong, and Lao communities" beats "a rich tapestry of cultures".',
  },
  {
    id: 'puffery-boasts',
    name: 'Promotional verb "boasts"',
    category: 'word-choice',
    regex: /\bboast(?:s|ed|ing)? (?:a|an|the|over|more than)\b/giu,
    why: 'Copula avoidance: plain "has" is replaced by an advertising verb to make a fact sound like praise.',
    suggestion: 'Use plain "has" and let the fact carry the weight.',
  },
  {
    id: 'puffery-nestled',
    name: 'Brochure cliché "nestled in the heart of"',
    category: 'phrase',
    regex: /\bnestled in the heart of\b|\bnestled (?:among|between|within)\b/giu,
    why: 'Travel-brochure puffery that substitutes atmosphere for a verifiable location.',
    suggestion: 'Give the actual location: "on Fifth Avenue between 42nd and 43rd".',
  },
  {
    id: 'symbolism-overreach',
    name: 'Unearned symbolism "a symbol of"',
    category: 'phrase',
    regex: /\ba symbol of\b|\bsymboliz(?:es|ing)\b|\bemblematic of\b/giu,
    minCount: 2,
    why: 'Editorializing overreach: broad symbolic meaning is assigned to a fact without evidence that anyone actually interpreted it that way.',
    suggestion: 'Attribute the interpretation to a named source, or delete the symbolic claim.',
  },
  {
    id: 'notability-media-puffery',
    name: 'Canned media-coverage claim',
    category: 'phrase',
    regex: /\b(?:profiled|featured) in (?:numerous|several|various|many) [\p{L} ]{0,20}(?:publications|media outlets|outlets|magazines)\b/giu,
    why: 'Formulaic notability inflation: it implies significance through unnamed coverage that cannot be verified.',
    suggestion: 'Name the specific outlet and link the piece, or remove the claim.',
  },
  {
    id: 'vague-attribution',
    name: 'Weasel attribution "experts agree"',
    category: 'phrase',
    regex: /\b(?:industry experts|experts|observers|some critics|many analysts|analysts) (?:agree|argue|note|say|believe|have (?:cited|noted|argued))\b/giu,
    why: 'Weasel wording: a claim is attributed to an unnamed authority, which makes it unfalsifiable.',
    suggestion: 'Name the actual source (author, publication, year), or cut the claim.',
  },
  {
    id: 'ghost-citation',
    name: 'Ghost citation "studies show"',
    category: 'phrase',
    regex: /\b(?:studies|research|data|surveys) (?:show|shows|prove|proves|suggest|suggests|indicate|indicates|confirm|confirms)\b/giu,
    why: 'Gestures at authority without naming a paper, author, or dataset — unlike genuine citation practice.',
    suggestion: 'Cite the study by author and year, or delete the sentence if no real source exists.',
  },
  {
    id: 'superficial-analysis-verbs',
    name: 'Tacked-on interpretive clause (", highlighting …")',
    category: 'structure',
    regex: /,\s*(?:highlighting|underscoring|emphasizing|reflecting|symbolizing|showcasing|signaling|cementing) \b/giu,
    minCount: 2,
    why: 'A dangling participle attaches an unsupported interpretive claim to a factual sentence (superficial analysis).',
    suggestion: 'Either justify the interpretation with evidence or delete the clause.',
  },
  {
    id: 'copula-avoidance',
    name: 'Copula avoidance "serves/functions as"',
    category: 'word-choice',
    regex: /\b(?:serves?|functions?|operates?|stands?) as (?:a|an|the)\b/giu,
    why: 'Plain "is" is replaced by an inflated verb to sound analytical (copula avoidance).',
    suggestion: 'Use "is/are" directly unless a genuine role distinction is meant.',
  },
  {
    id: 'negative-parallelism-not-only',
    name: 'Template "not only X but also Y"',
    category: 'structure',
    regex: /\bnot only\b[^.!?\n]{2,80}?\bbut(?: also| rather)?\b/giu,
    minCount: 2,
    why: 'A parallel-emphasis template generated text repeats far beyond human baseline; once is a choice, several times is a pattern.',
    suggestion: 'Keep at most one; rewrite the others as direct statements or a plain "and".',
  },
  {
    id: 'negative-parallelism-not-just',
    name: 'Template "it\'s not just X, it\'s Y"',
    category: 'structure',
    regex: /\bit['’]?s not (?:just |only |merely |about )?[^.!?\n]{2,60}?,? it['’]?s (?:about )?/giu,
    why: 'A rhetorical antithesis template used as a default emphasis device rather than a deliberate choice (negative parallelism).',
    suggestion: 'Cut the setup clause and state the point once, directly.',
  },
  {
    id: 'negative-parallelism-rather-than',
    name: 'Template "prioritizing X rather than Y"',
    category: 'structure',
    regex: /\b(?:prioritizing|focusing on|emphasizing) [^.!?\n]{2,50}?\brather than\b/giu,
    minCount: 2,
    why: 'The balanced "X rather than Y" contrast frame is a construction LLMs reach for reflexively.',
    suggestion: 'State the priority directly unless the contrast is genuinely the point.',
  },
  {
    id: 'rule-of-three',
    name: 'Rule-of-three triads',
    category: 'structure',
    regex: /(?<![\p{L}\p{N}])[\p{L}\p{N}'’-]+(?: [\p{L}\p{N}'’-]+){0,2}, [\p{L}\p{N}'’-]+(?: [\p{L}\p{N}'’-]+){0,2},? (?:and|or) [\p{L}\p{N}'’-]+/giu,
    minCount: 2,
    why: 'LLMs default to tricolon groupings ("bold, ambitious, and transformative") for rhythm even when only two items are warranted; repeated triads are the tell.',
    suggestion: 'Cut each list to the number of items actually needed instead of padding to three.',
  },
  {
    id: 'outline-challenges-future',
    name: 'Template "despite X, faces several challenges"',
    category: 'structure',
    regex: /\bdespite (?:its|their|these|his|her) [^.!?\n]{2,60}?,? (?:it|they|the \p{L}+) (?:faces?|continues? to face) (?:several|numerous|a number of|many) challenges\b/giu,
    why: 'A templated "challenges and outlook" move that concedes unspecified successes and unspecified problems — balanced-sounding but content-free.',
    suggestion: 'Name the actual challenges with sources, or delete the sentence.',
  },
  {
    id: 'section-summary-ending',
    name: 'Formulaic conclusion "in conclusion"',
    category: 'structure',
    regex: /(?:^|(?<=[.!?]\s))(?:in (?:summary|conclusion|closing)|to conclude|to summarize|to sum up|overall,|all in all)/gim,
    why: 'Schoolbook summary openers signal a restate-the-thesis template; generated essays almost always close with one.',
    suggestion: 'End with your strongest concrete point or its consequence — not a restatement.',
  },
  {
    id: 'formulaic-transitions',
    name: 'Formulaic transitions (Moreover, Furthermore …)',
    category: 'structure',
    regex: /(?:^|(?<=[.!?]\s))(?:Moreover|Furthermore|Additionally|In addition|Notably|Importantly),\s/gmu,
    minCount: 3,
    why: 'These connectives are individually fine, but generated text opens paragraph after paragraph with one, producing a mechanical rhythm instead of real logical links.',
    suggestion: 'Cut the transition from at least half of these sentences, or name the actual relation: "because", "as a result", "for example".',
  },
  {
    id: 'rhetorical-question-triad',
    name: 'Staged rhetorical questions',
    category: 'structure',
    regex: /(?:^|\n)[A-Z][^.?!\n]{5,80}\?\s+[A-Z][^.?!\n]{5,80}\?/gu,
    why: 'Consecutive rhetorical questions that the author immediately answers simulate inquiry rather than pose real questions — a staging device typical of generated essays.',
    suggestion: 'Replace the question pair with a direct statement of the point they lead to.',
  },
  {
    id: 'landscape-realm',
    name: 'Abstract "landscape/realm" metaphor',
    category: 'word-choice',
    phrases: ['in the realm of', 'navigating the landscape', 'navigate the landscape', 'ever-evolving landscape', 'ever-changing landscape', 'navigate the complexities', 'navigating the complexities'],
    why: 'Spatial metaphors for abstract domains sound sophisticated but carry no information; generated text uses them as safe filler.',
    suggestion: 'Name the field plainly: "in web development", "in tax law".',
  },
  {
    id: 'ai-vocab-core',
    name: 'AI-vocabulary cluster (delve, underscore, pivotal …)',
    category: 'word-choice',
    regex: /\b(?:delve[sd]?|delving|underscor(?:e|es|ed|ing)|meticulous(?:ly)?|intricate(?:ly)?|intricacies|tapestry|testament|garner(?:s|ed|ing)?|bolster(?:s|ed|ing)?|pivotal|vibrant|paramount|multifaceted|realm|landscape|myriad)\b/giu,
    minCount: 3,
    minPer1000Words: 8,
    why: 'These "focal words" spiked in frequency after LLMs became widespread; each is unremarkable alone, but a cluster in one passage is a strong statistical tell.',
    suggestion: 'Swap each for a plain, specific word; if several cluster in one paragraph, rewrite the passage rather than word-by-word.',
  },
  {
    id: 'ai-vocab-verbs',
    name: 'Generic uplift verbs (foster, enhance, showcase …)',
    category: 'word-choice',
    regex: /\b(?:foster(?:s|ing)?|enhanc(?:e|es|ed|ing)|showcas(?:e|es|ed|ing)|highlight(?:s|ed|ing)?|align(?:s|ed|ing)? with|empower(?:s|ed|ing)?)\b/giu,
    minCount: 3,
    minPer1000Words: 10,
    why: 'A verb rotation LLMs use to make any activity sound constructive without saying what actually happened.',
    suggestion: 'Replace each with the concrete verb for what happened: "trained", "paid for", "published".',
  },
  {
    id: 'academic-marker-words',
    name: 'Academic marker-word cluster',
    category: 'word-choice',
    regex: /\b(?:across|additionally|comprehensive|crucial(?:ly)?|enhancing|exhibited|insights?|notably|particularly|within)\b/giu,
    minCount: 4,
    minPer1000Words: 25,
    why: 'This word set was identified in large-scale studies of scientific abstracts as the most diagnostic cluster of LLM-assisted text; density, not any single word, is the signal.',
    suggestion: 'Trim clauses that only restate emphasis; keep the words that carry real information.',
  },
  {
    id: 'academic-adjectives',
    name: 'Inflated review adjectives (commendable, meticulous …)',
    category: 'word-choice',
    regex: /\b(?:commendable|meticulous(?:ly)?|intricate(?:ly)?|innovative|versatile|invaluable|noteworthy)\b/giu,
    minCount: 3,
    minPer1000Words: 10,
    why: 'Corpus studies of peer reviews measured these evaluative adjectives rising sharply in LLM-assisted text; they praise without substantiating.',
    suggestion: 'Replace with a specific, checkable judgment: "the ablation in Section 4 isolates the variable cleanly".',
  },
  {
    id: 'buzzword-cluster',
    name: 'Corporate buzzword cluster (leverage, seamless, robust …)',
    category: 'word-choice',
    regex: /\b(?:leverag(?:e|es|ed|ing)|seamless(?:ly)?|robust|holistic|streamlin(?:e|es|ed|ing)|synerg(?:y|ies|istic)|paradigm|ecosystem|cutting-edge|state-of-the-art|game[- ]chang(?:er|ing)|best[- ]practices?|at scale)\b/giu,
    minCount: 3,
    minPer1000Words: 10,
    why: 'A buzzword-dense corporate register that LLMs reproduce by default; the density of interchangeable quality-words signals templated generation.',
    suggestion: 'Replace each with a verifiable property: "installs in one step", "handles 10k requests per second".',
  },
  {
    id: 'marketing-hype',
    name: 'Marketing hype verbs (unleash, unlock, elevate …)',
    category: 'tone',
    phrases: ['unleash', 'unlock the power', 'unlock the potential', 'unlock your', 'elevate your', 'supercharge', 'game-changer', 'game changer', 'revolutionize', 'transformative power'],
    why: 'Inflated promotional verbs (hyperbole) promise transformation instead of describing function — typical of generated marketing copy.',
    suggestion: 'Describe the concrete benefit: what does the reader get, measured how?',
  },
  {
    id: 'em-dash-overuse',
    name: 'Em-dash overuse',
    category: 'punctuation',
    regex: /—|(?<=\s)–(?=\s)|(?<=\s)--(?=\s)/gu,
    minCount: 3,
    minPer1000Words: 10,
    why: 'Current LLMs insert parenthetical dashes at well above the human baseline; a high density is one of the most visible formatting fingerprints.',
    suggestion: 'Convert most dashes to commas, colons, or separate sentences; keep one deliberate break at most per paragraph.',
  },
  {
    id: 'knowledge-cutoff-disclaimer',
    name: 'Knowledge-cutoff disclaimer',
    category: 'chatbot-artifact',
    regex: /\bas of my (?:last )?(?:knowledge cutoff|training data|update)\b|\bi (?:don['’]t|do not) have (?:access to real[- ]time|access to the internet|real[- ]time)\b|\bi cannot browse\b|\bas an ai(?: language)? model\b|\bi['’]m (?:an ai|just an ai)\b/giu,
    why: 'A disclaimer only a language model produces, referencing its own training — unambiguous evidence of unedited chatbot output.',
    suggestion: 'Delete the sentence; replace with an actual as-of date if the caveat matters.',
  },
  {
    id: 'chatbot-pleasantries',
    name: 'Chatbot pleasantries ("Certainly!", "I hope this helps")',
    category: 'chatbot-artifact',
    regex: /(?:^|\n)(?:certainly|sure|of course|absolutely|great question)[!.]\s|i hope (?:this|that) helps|is there anything else i can|let me know if you (?:need|have|want)/giu,
    minCount: 2,
    why: 'Conversational turn-markers addressed to a chat user (opening acknowledgment, closing offer of help) that survived a copy-paste; one polite closer is normal in an email, the opener-plus-closer pair is the chatbot fingerprint.',
    suggestion: 'Delete the pleasantries; keep only the substantive content.',
  },
  {
    id: 'refusal-artifact',
    name: 'Prompt-refusal leftover',
    category: 'chatbot-artifact',
    regex: /\bi['’]m sorry,? but i (?:can['’]?t|cannot)\b|\bi (?:cannot|can['’]?t|am unable to) (?:provide|assist|help with|generate|write)\b/giu,
    why: 'A refusal generated in response to the original prompt that was never removed — the passage began life as a chatbot reply.',
    suggestion: 'Delete it and write the intended content directly.',
  },
  {
    id: 'citation-artifact',
    name: 'Broken LLM citation markup',
    category: 'chatbot-artifact',
    regex: /\b(?:contentReference|oaicite|oai_citation|turn\d+search\d+|attributableIndex|utm_source=chatgpt)\b|\[cite:\s*\d+\]/gu,
    why: 'Internal citation tokens from chatbot interfaces that leak into copied output — a mechanical fingerprint, not a style judgment.',
    suggestion: 'Remove the token and add a real citation, or delete the claim if unsupported.',
  },
  {
    id: 'title-case-headings',
    name: 'Mechanically title-cased headings',
    category: 'structure',
    raw: true,
    regex: /^#{1,6}[ \t]+(?=(?:\S+ ){3,})(?:[A-Z0-9]\S* )*(?:Of|The|A|An|And|Or|In|For|To|With|On|At)(?: [A-Z0-9]\S*)+[ \t]*$/gmu,
    why: 'Capitalizing every word including "of/the/and" is the mechanical title-casing LLMs default to; standard style is sentence case with only proper nouns capitalized.',
    suggestion: 'Use sentence case: capitalize only the first word and proper nouns.',
  },
  {
    id: 'inline-header-bullets',
    name: 'Bolded pseudo-header bullets',
    category: 'structure',
    raw: true,
    regex: /^[ \t]*[-*•–][ \t]+\*\*[^*\n]+\*\*[:：]/gmu,
    minCount: 2,
    why: 'Bullet + bolded label + colon is a chatbot outline habit substituting for prose paragraphs (inline-header vertical lists). In a reference list (config options, API parameters) this format is legitimate — the tell is when it replaces explanatory prose.',
    suggestion: 'In explanatory text, convert the list to sentences or real headings; ignore this for genuine reference lists.',
  },
  {
    id: 'bold-overuse',
    name: 'Mechanical bold overuse',
    category: 'structure',
    raw: true,
    regex: /\*\*[^*\n]+\*\*/gu,
    minCount: 5,
    minPer1000Words: 20,
    why: 'LLMs mechanically bold "key terms" at a much higher density than human editors use for genuine emphasis. Definition-style reference lists are a legitimate exception.',
    suggestion: 'In prose, reserve bold for the one genuinely critical term per section; ignore this for reference lists.',
  },
  {
    id: 'emoji-formatting',
    name: 'Emoji as section markers',
    category: 'structure',
    raw: true,
    regex: /^[ \t]*[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}][ \t]*(?:\*\*|#|[A-Z])/gmu,
    minCount: 2,
    why: 'Emoji used to structure content sections is a distinctively chatbot-derived formatting habit.',
    suggestion: 'Remove decorative emoji; let real headings carry the structure.',
  },
]
