import type { Pattern } from './patterns'

export const DE_SPEAKER_TELLS: Pattern[] = [
  {
    id: 'since-years',
    name: '"Since five years" (seit + Dauer)',
    category: 'german-speaker-tell',
    regex: /\bsince (?:\d+|one|two|three|four|five|six|seven|eight|nine|ten|many|several|a few) (?:year|month|week|day|hour)s?\b/giu,
    why: 'Transfer from German "seit fünf Jahren": English uses "for" with durations and "since" only with points in time.',
    suggestion: 'Use "for five years" (duration) or "since 2021" (starting point).',
  },
  {
    id: 'informations',
    name: 'Uncountable plural ("informations")',
    category: 'german-speaker-tell',
    phrases: ['informations', 'feedbacks', 'advices', 'knowledges'],
    why: 'German "Informationen" is countable, but the English equivalents are mass nouns and have no plural.',
    suggestion: 'Use "information", "feedback", "advice" — add "pieces of" if you must count them.',
  },
  {
    id: 'comma-before-that',
    name: 'German comma before "that"-clause',
    category: 'german-speaker-tell',
    regex: /,\s+that (?:the|a|an|it|we|you|they|he|she|i|this|these|those|there)\b/giu,
    why: 'German grammar requires a comma before every "dass"-clause; English never separates a conjunction "that"-clause with a comma.',
    suggestion: 'Delete the comma: "I think that we should…", not "I think, that we should…".',
  },
  {
    id: 'how-looks-like',
    name: '"How it looks like" (wie es aussieht)',
    category: 'german-speaker-tell',
    regex: /\bhow (?:it|this|that|she|he|the \p{L}+) looks? like\b|\bhow does [^.!?\n]{0,20}look like\b/giu,
    why: 'A blend of German "wie es aussieht" with English: use either "how it looks" or "what it looks like" — never both.',
    suggestion: 'Write "what it looks like" or "how it looks".',
  },
  {
    id: 'we-see-us',
    name: '"We see us" (wir sehen uns)',
    category: 'german-speaker-tell',
    phrases: ['we see us', 'see us tomorrow', 'see us next week'],
    why: 'Direct transfer of the reflexive "wir sehen uns"; English uses "see each other" or a plain future.',
    suggestion: 'Use "see you tomorrow" or "we\'ll see each other tomorrow".',
  },
  {
    id: 'by-foot',
    name: '"By foot" (zu Fuß)',
    category: 'german-speaker-tell',
    phrases: ['by foot'],
    why: 'Transfer from "zu Fuß" via the by-pattern of "by car/by bus"; idiomatic English is "on foot".',
    suggestion: 'Use "on foot" (or "I walk to work").',
  },
  {
    id: 'handy-phone',
    name: '"Handy" for mobile phone',
    category: 'german-speaker-tell',
    regex: /\b(?:my|your|his|her|our|their) handy\b(?= ?(?:is|was|has|had|rang|broke|died)\b|[.,;!?])/giu,
    why: '"Handy" is a German pseudo-anglicism; in English it is only an adjective meaning "useful".',
    suggestion: 'Use "phone", "mobile", or "cell phone".',
  },
  {
    id: 'until-now',
    name: '"Until now" for "bis jetzt"',
    category: 'german-speaker-tell',
    phrases: ['until now'],
    why: '"Until now" implies the situation has just changed; German "bis jetzt" usually means "so far" (still true).',
    suggestion: 'Use "so far" if the situation continues; keep "until now" only when it just changed.',
  },
  {
    id: 'persons-people',
    name: '"Persons" instead of "people"',
    category: 'german-speaker-tell',
    phrases: ['persons'],
    why: 'German "Personen" maps to "persons", but outside legal or technical register English uses "people".',
    suggestion: 'Use "people" ("three people attended"); reserve "persons" for legal texts.',
  },
  {
    id: 'become-receive',
    name: '"Become" for "bekommen"',
    category: 'german-speaker-tell',
    regex: /\bbecome (?:a |an |the |any )?(?:present|gift|letter|call|phone call|email|e-mail|answer|reply|message|money|invoice|visa)\b/giu,
    why: 'False friend: German "bekommen" means "to receive"; English "become" means "to turn into".',
    suggestion: 'Use "get" or "receive": "I got an email", not "I became an email".',
  },
  {
    id: 'make-do',
    name: '"Make" for German "machen" collocations',
    category: 'german-speaker-tell',
    regex: /\bmake (?:my |your |our |their |his |her |some |a |an )?(?:homework|photos?|picture of|holidays?|break|experiences?|sport|party)\b/giu,
    why: 'German uses "machen" universally, but English collocations differ: do homework, take a photo, take a break, do sports, throw a party.',
    suggestion: 'Check the collocation: "do homework", "take a photo", "take a break", "go on holiday".',
  },
  {
    id: 'actual-current',
    name: '"Actual" for "aktuell"',
    category: 'german-speaker-tell',
    regex: /\bactual (?:situation|status|version|state|data|numbers)\b/giu,
    why: 'False friend: German "aktuell" means "current/up to date"; English "actual" means "real, in fact".',
    suggestion: 'Use "current": "the current version", unless you really mean "the real one as opposed to the assumed one".',
  },
]
